name: PUSH
on:
  push:
    paths:
      - "iptables/dmit-hk/release.md"
env:
  XRAY_DIR: iptables/dmit-hk/iptables.conf

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d%H%M')"
        shell: bash
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY }}
          source: "./${{ env.XRAY_DIR }}"
          target: "/root"
      - name: restore iptables from file
        uses: appleboy/ssh-action@master
        with:
          overwrite: true
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            iptables-restore < iptables.conf
            /usr/sbin/netfilter-persistent save
            echo "${{ steps.date.outputs.today }}" >> it_change
