name: PUSH
on:
  push:
    paths:
      - "xray/release.md"
env:
  XRAY_VERSION: v1.6.5
  XRAY_DIR: xray

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d%H%M')"
        shell: bash
      - name: Reponse body
        id: response_info_1
        run: |
          cd ${{ env.XRAY_DIR }}
          ls -all
          ls -all
          result=$(ls |wc -l)
          rs='false'
          echo $result"................."
          if [[ result -gt 0 ]];then
            rs='true'
          fi
          echo "::set-output name=run_project_b_build::${rs}"

      - name: Build project
        if: ${{ steps.response_info_1.outputs.run_project_b_build == 'true' }}
        run: |
          cd ${{ env.XRAY_DIR }}
          wget -v https://github.com/XTLS/Xray-core/releases/download/${{ env.XRAY_VERSION }}/Xray-linux-64.zip
          cd ../
          pwd
          ls -all ${{ env.XRAY_DIR }}/
      - name: copy file via ssh key
        if: ${{ steps.response_info_1.outputs.run_project_b_build == 'true' }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY }}
          source: "./${{ env.XRAY_DIR }}"
          target: "/root"
      - name: mv ./xray to outside
        if: ${{ steps.response_info_1.outputs.run_project_b_build == 'true' }}
        uses: appleboy/ssh-action@master
        with:
          overwrite: true
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            apt install -y curl gnupg2 ca-certificates lsb-release debian-archive-keyring
            curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor     | tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
            gpg --dry-run --quiet --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
            http://nginx.org/packages/debian `lsb_release -cs` nginx"     | tee /etc/apt/sources.list.d/nginx.list
            echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
            http://nginx.org/packages/mainline/debian `lsb_release -cs` nginx"     | tee /etc/apt/sources.list.d/nginx.list
            echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n"     | tee /etc/apt/preferences.d/99nginx
            apt update
            apt install -y nginx

            apt install -y net-tools
            apt install -y vnstat vnstati
            chmod +x /root/vnstat.sh

            cd /root/${{ env.XRAY_DIR }}
            cat sysctl.conf >> /etc/sysctl.conf
            sysctl -p
            rm -rf /etc/localtime
            ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
            
            apt install -y unzip
            unzip Xray-linux-64.zip
            rm -rf Xray-linux-64.zip
            chmod +x xray
            /usr/bin/wget -v -N  https://github.com/crab21/v2ray-rules-dat/releases/latest/download/geoip.dat -O /root/xray/geoip.dat
            /usr/bin/wget -v -N  https://github.com/crab21/v2ray-rules-dat/releases/latest/download/geosite.dat -O /root/xray/geosite.dat
            
            mv -f xray.service /etc/systemd/system/xray.service
            mv -f xray1445.service /etc/systemd/system/xray1445.service
            mv -f xray1446.service /etc/systemd/system/xray1446.service
            systemctl enable --now xray

            systemctl enable --now xray1445
            systemctl enable --now xray1446
            cd /root/${{ env.XRAY_DIR }}
            mv -f ws/xray_ws.service /etc/systemd/system/xray_ws.service
            mv -f nginx.conf /etc/nginx/conf.d/ws.conf
            # systemctl enable xray_ws
            # systemctl start xray_ws
            
            # nginx -s reload
            # systemctl restart nginx


      - name: git push change file
        if: ${{ steps.response_info_1.outputs.run_project_b_build == 'true' }}
        continue-on-error: true
        run: |
          git config --local user.name "crab"
          git config --local user.email "imrcrab@163.com"
          git add ${{ env.XRAY_DIR }}/version.yml
          git commit -m "modify: auto by action"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/crab21/vps_deploy.git
          rm -rf ~/.ssh
